// <auto-generated />
namespace FundApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _0019 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_0019));
        
        string IMigrationMetadata.Id
        {
            get { return "201404302019576_0019"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
