// <auto-generated />
namespace FundApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _2355 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2355));
        
        string IMigrationMetadata.Id
        {
            get { return "201405011955360_2355"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
