// <auto-generated />
namespace FundApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _1011 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1011));
        
        string IMigrationMetadata.Id
        {
            get { return "201405200611207_1011"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
