// <auto-generated />
namespace FundApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _1555 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1555));
        
        string IMigrationMetadata.Id
        {
            get { return "201405111155389_1555"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
