// <auto-generated />
namespace FundApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FundDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FundDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201404241937339_FundDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
